### ISSUE TITLE
Problem with discs

### ISSUE THREAD

**Issue by ghost** [rickgaiser/kernelloader#1]
Hello, actually I don't know if this is a correct place to send this issue(?), I was following this [guide](http://kernelloader.sourceforge.net/tutorial/howtoinstalllinux.html), however using the newer versions Linux 2.6 and Kernel Loader 3.0, everything goes right when I stop in the disc formating part, /dev/ide doesn't exists, so I assume it isn't devfs, tryed /dev/hda, the file exists but can't open it, if I do a `fdisk -l` it don't show any discs that can be formated.
Thanks anyway. If you need any information about hardware tell me please

**Comment by rickgaiser** [comment]
That guide was created by @jur. He was the original developer of kernelloader and creator of the linux 2.6 port. I later continued some of his work and created a linux 3.8 port.

I created a usb stick demo release that should be easy to install:
- v0.1 [here](http://psx-scene.com/forums/f167/release-linux-3-8-usb-demo-stick-154637/)
- v0.2 [here](http://psx-scene.com/forums/f167/porting-linux-2-6-ps2-67806/index69.html#post1208922)

**Comment by ghost** [comment]
thanks
